### ISSUE TITLE
FLINK Kinesis Connector Error - ProvisionedThroughputExceededException

### ISSUE THREAD

**Issue by sbistline** [aws-samples/realtime-bushfire-alert-with-apache-flink-cep#1]
I am getting this error from the Flink Kinesis Connector. I have a native KCL app running in parallel with no problems. 

Any help would be appreciated

Thanks so much!!
Steve
===================================================
flink-sbistl919-taskexecutor-0-CACSVML-15736.log:2018-11-09 07:46:11,579 WARN  org.apache.flink.streaming.connectors.kinesis.proxy.KinesisProxy  - Got recoverable SdkClientException. Backing off for 258 millis (Rate exceeded for shard shardId-000000000000 in stream CSV under account  xxxxxxxxx  . (Service: AmazonKinesis; Status Code: 400; Error Code: ProvisionedThroughputExceededException; Request ID: e1c0caa4-8c4c-7738-b59f-4977bc762cf3))

flink-sbistl919-taskexecutor-0-CACSVML-15736.log:2018-11-09 07:46:16,844 WARN  org.apache.flink.streaming.connectors.kinesis.proxy.KinesisProxy  - Got recoverable SdkClientException. Backing off for 203 millis (Rate exceeded for shard shardId-000000000001 in stream CSV under account xxxxxxxxx. (Service: AmazonKinesis; Status Code: 400; Error Code: ProvisionedThroughputExceededException; Request ID: f7d22c26-96f6-c547-a38d-affe493cd2e1))

**Comment by Amay22** [comment]
+1 I wanna know too

**Comment by joarder** [comment]
The "ProvisionedThroughputExceededException" is generated by the KCL connector (which is used internally by Flink to consume from Kinesis stream source) when the shard level limits are hit from the GetRecords API calls. Usually, these failed attempts are retried by KCL, therefore, unless you see the records coming out in the consumer end this should not be a matter of concern.
